gitSafeReplacementChar: '-'
branchName: '${issue.title,}' # `,` for all lowercase

# `issue-` is required for `autoCloseIssue`
branches:
  - label: bug
    prefix: fix/issue-${issue.number}/
  - label: feature
    prefix: feature/issue-${issue.number}/
  - label: doc
    prefix: doc/issue-${issue.number}/
  - label: QA
    prefix: qa/issue-${issue.number}/
  - label: '*'
    skip: true

openDraftPR: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true

commentMessage: 'Branch [`${branchName}`](${repository.html_url}/tree/${branchName}) created for issue #${issue.number}.'