gitSafeReplacementChar: '-'
branchName: '${issue.title,}' # `,` for all lowercase

branches:
  - label: bug
    prefix: fix/${issue.number}/
  - label: feature
    prefix: feature/${issue.number}/
  - label: doc
    prefix: doc/${issue.number}/
  - label: QA
    prefix: qa/${issue.number}/
  - label: '*'
    skip: true

openDraftPR: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true

commentMessage: 'Branch [`${branchName}`](${repository.html_url}/tree/${branchName}) created for issue #${issue.number}.'