/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.chevrygames.game.math;

public class Library {

    public boolean someLibraryMethod() {
        return true;
    }
}
